server:
  port: 8082

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD:AS04SERa1}

  mail:
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}


services:
  auth-service: http://localhost:8085


service:
  client-id: register-service
  client-secret: ${REGISTER_SECRET:register_secret}