jwt:
  secret: 4eaee43cfe4d9d08e6391dab67baf143
  expiration:
    users: 900000 #15 min
    service: 300000 #5 min

  refresh:
    expirationMs: 604800000 #7 суток

server:
  port: 8085
frontend:
  url: http://localhost:8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/security_users_db
    username: alexgls
    password: AS04SERa1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/.well-known/jwks.json

services:
  register:
    id: register-service
    secret: ${REGISTER_SECRET:register_secret}
