server:
  port: 8094

spring:
  kafka:
    bootstrap-servers: localhost:29092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/.well-known/jwks.json

services:
  auth-service: http://localhost:8085

ai-services:
  gigachat:
    auth-url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    ai-url: https://gigachat.devices.sberbank.ru/api/v1
    load-files-url: https://gigachat.devices.sberbank.ru/api/v1/files
    chat-url: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
    auth-token: ${SBER_AUTH_TOKEN}